name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository
        uses: actions/checkout@v3

      - name: Python install
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Poetry install
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install